title: The Quadratic Formula
description: >-
  Find the roots of any quadratic equation by entering the coefficients of the
  polynomial.
template:
  repo: the-quadratic-formula-template
  name: the-quadratic-formula
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
